# Auto-generated by mtbmcp. Do not edit manually.
import json as _json

SESSION_INFO = _json.loads(r'''{
  "extension_dir": "c:/Users/uwais/.vscode/extensions/infineonag.modustoolbox-ai-0.2.1-win32-x64",
  "workspace_path": "c:/Users/uwais/Desktop/Infineon_FPGA_SOC_workshop_JULY2026/projects/miniproject_guitar_drum_with_PSOC6",
  "projects": [
    "miniproject_guitar_drum_with_PSOC6"
  ],
  "device_name": "CY8C624ABZI-S2D44",
  "bsp_name": "APP_CY8CPROTO-062-4343W",
  "board_target": "TARGET_APP_CY8CPROTO-062-4343W",
  "cy_tools_path": "C:/Users/uwais/ModusToolbox/tools_3.8",
  "modus_shell_path": "C:/Users/uwais/ModusToolbox/tools_3.8/modus-shell",
  "tcp_port": 52539,
  "ext_port": 52538,
  "pid": 22008,
  "log_level": "info",
  "log_file": "C:/Users/uwais/AppData/Local/Temp/mtbai-logs/mtbai.log"
}''')

for _key, _value in SESSION_INFO.items():
    globals()[_key.upper()] = _value

del _json
del _key
del _value
